version: '3'
services:
  store:
    container_name: store_app
    image: store_app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresdatabase
      - pg

  postgresdatabase:
    image: postgres
    container_name: 'postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=store
      - POSTGRES_HOST_AUTH_METHOD=trust

  pg:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"